export { defineConfig, defaultConfig } from './config/schema.js'
export type { Config } from './config/schema.js'
export { loadConfig } from './config/loader.js'
export { getProtectedPaths, getStagedFiles, matchesPatterns, fileExistsInBranch } from './core/resolver.js'
export { calculateScore } from './core/score.js'
export type { IntegrityScore, AnalyzerResults, Weights } from './core/score.js'
export { extractScores, checkMutationThresholds, mergeMutationReports } from './analyzers/mutation.js'
export type { MutationReport, CountedMutationReport, MutationConfig, SurvivedMutant } from './analyzers/mutation.js'
export {
  detectWeakeningInDiff,
  detectWeakeningWithAdapter,
  compareExtractions,
  ASSERTION_STRENGTH,
} from './analyzers/semantic-diff.js'
export type { WeakeningViolation, WeakeningPattern, TestExtraction } from './analyzers/semantic-diff.js'
export type { ExtractedTest, ExtractedAssertion, SetupStatement } from './analyzers/test-ast.js'
export { registerAdapter, getAdapter, resolveLanguages, languageForFile } from './languages/registry.js'
export { runMutationForLanguages } from './languages/mutation.js'
export { typescriptAdapter } from './languages/typescript.js'
export { goAdapter, createGoAdapter, GO_ASSERTION_STRENGTH } from './languages/go.js'
export type { GoAdapterOptions } from './languages/go.js'
export { dartAdapter, createDartAdapter, DART_ASSERTION_STRENGTH } from './languages/dart.js'
export type { DartAdapterOptions } from './languages/dart.js'
export type { LanguageAdapter, ResolvedLanguage, MutationRunOptions } from './languages/types.js'
export { detectGoldenUpdates, resolveRelatedFile, extraGoldenTestFiles } from './analyzers/golden-diff.js'
export type { GoldenSide } from './analyzers/golden-diff.js'
export { formatReport } from './reporters/console.js'
export { runCheck } from './cli/runner.js'
export { classifyStaged, runPreCommit } from './hooks/pre-commit.js'
export { checkProtectedTests, isProtectedTestFile } from './analyzers/protected-tests.js'
export type { ProtectedTestViolation } from './analyzers/protected-tests.js'
export { detectConfigWeakening } from './analyzers/config-diff.js'
export type { ConfigWeakeningViolation } from './analyzers/config-diff.js'
export type { CheckResult, AnalyzerInputs } from './cli/runner.js'
